name: flutter_nes
description: A nes emulator.
version: 0.0.1
author: mao.zheng
homepage: https://github.com/mao0613/flutter_nes

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
