part of "cpu.dart";

class Op {
  Op(this.instruction, this.mode, this.cycles, [this.increaseCycleWhenCrossPage = false]);

  final Instruction instruction;
  final AddressMode mode;
  final int cycles;
  final bool increaseCycleWhenCrossPage;
}

final Map<int, Op> OP_TABLE = {
  0x69: Op(ADC, Immediate, 2),
  0x65: Op(ADC, ZeroPage, 3),
  0x75: Op(ADC, ZeroPageX, 4),
  0x6d: Op(ADC, Absolute, 4),
  0x7d: Op(ADC, AbsoluteX, 4, true),
  0x79: Op(ADC, AbsoluteY, 4, true),
  0x61: Op(ADC, IndexedIndirect, 6),
  0x71: Op(ADC, IndirectIndexed, 5, true),
  0x29: Op(AND, Immediate, 2),
  0x25: Op(AND, ZeroPage, 3),
  0x35: Op(AND, ZeroPageX, 4),
  0x2d: Op(AND, Absolute, 4),
  0x3d: Op(AND, AbsoluteX, 4, true),
  0x39: Op(AND, AbsoluteY, 4, true),
  0x21: Op(AND, IndexedIndirect, 6),
  0x31: Op(AND, IndirectIndexed, 5, true),
  0x0a: Op(ASL, Accumulator, 2),
  0x06: Op(ASL, ZeroPage, 5),
  0x16: Op(ASL, ZeroPageX, 6),
  0x0e: Op(ASL, Absolute, 6),
  0x1e: Op(ASL, AbsoluteX, 7),
  0x90: Op(BCC, Relative, 2, true),
  0xb0: Op(BCS, Relative, 2, true),
  0xf0: Op(BEQ, Relative, 2, true),
  0x24: Op(BIT, ZeroPage, 3),
  0x2c: Op(BIT, Absolute, 4),
  0x30: Op(BMI, Relative, 2, true),
  0xd0: Op(BNE, Relative, 2, true),
  0x10: Op(BPL, Relative, 2, true),
  0x00: Op(BRK, Implied, 7),
  0x50: Op(BVC, Relative, 2, true),
  0x70: Op(BVS, Relative, 2, true),
  0x18: Op(CLC, Implied, 2),
  0xd8: Op(CLD, Implied, 2),
  0x58: Op(CLI, Implied, 2),
  0xb8: Op(CLV, Implied, 2),
  0xc9: Op(CMP, Immediate, 2),
  0xc5: Op(CMP, ZeroPage, 3),
  0xd5: Op(CMP, ZeroPageX, 4),
  0xcd: Op(CMP, Absolute, 4),
  0xdd: Op(CMP, AbsoluteX, 4, true),
  0xd9: Op(CMP, AbsoluteY, 4, true),
  0xc1: Op(CMP, IndexedIndirect, 6, true),
  0xd1: Op(CMP, IndirectIndexed, 5, true),
  0xe0: Op(CPX, Immediate, 2),
  0xe4: Op(CPX, ZeroPage, 3),
  0xec: Op(CPX, Absolute, 4),
  0xc0: Op(CPY, Immediate, 2),
  0xc4: Op(CPY, ZeroPage, 3),
  0xcc: Op(CPY, Absolute, 4),
  0xc6: Op(DEC, ZeroPage, 5),
  0xd6: Op(DEC, ZeroPageX, 6),
  0xce: Op(DEC, Absolute, 6),
  0xde: Op(DEC, AbsoluteX, 7),
  0xca: Op(DEX, Implied, 2),
  0x88: Op(DEY, Implied, 2),
  0x49: Op(EOR, Immediate, 2),
  0x45: Op(EOR, ZeroPage, 3),
  0x55: Op(EOR, ZeroPageX, 4),
  0x4d: Op(EOR, Absolute, 4),
  0x5d: Op(EOR, AbsoluteX, 4, true),
  0x59: Op(EOR, AbsoluteY, 4, true),
  0x41: Op(EOR, IndexedIndirect, 6),
  0x51: Op(EOR, IndirectIndexed, 5, true),
  0xe6: Op(INC, ZeroPage, 5),
  0xf6: Op(INC, ZeroPageX, 6),
  0xee: Op(INC, Absolute, 6),
  0xfe: Op(INC, AbsoluteX, 7),
  0xe8: Op(INX, Implied, 2),
  0xc8: Op(INY, Implied, 2),
  0x4c: Op(JMP, Absolute, 3),
  0x6c: Op(JMP, Indirect, 5),
  0x20: Op(JSR, Absolute, 6),
  0xa9: Op(LDA, Immediate, 2),
  0xa5: Op(LDA, ZeroPage, 3),
  0xb5: Op(LDA, ZeroPageX, 4),
  0xad: Op(LDA, Absolute, 4),
  0xbd: Op(LDA, AbsoluteX, 4, true),
  0xb9: Op(LDA, AbsoluteY, 4, true),
  0xa1: Op(LDA, IndexedIndirect, 6),
  0xb1: Op(LDA, IndirectIndexed, 5, true),
  0xa2: Op(LDX, Immediate, 2),
  0xa6: Op(LDX, ZeroPage, 3),
  0xb6: Op(LDX, ZeroPageY, 4),
  0xae: Op(LDX, Absolute, 4),
  0xbe: Op(LDX, AbsoluteY, 4, true),
  0xa0: Op(LDY, Immediate, 2),
  0xa4: Op(LDY, ZeroPage, 3),
  0xb4: Op(LDY, ZeroPageX, 4),
  0xac: Op(LDY, Absolute, 4),
  0xbc: Op(LDY, AbsoluteX, 4, true),
  0x4a: Op(LSR, Accumulator, 2),
  0x46: Op(LSR, ZeroPage, 5),
  0x56: Op(LSR, ZeroPageX, 6),
  0x4e: Op(LSR, Absolute, 6),
  0x5e: Op(LSR, AbsoluteX, 7),
  0x1a: Op(NOP, Implied, 2),
  0x3a: Op(NOP, Implied, 2),
  0x5a: Op(NOP, Implied, 2),
  0x7a: Op(NOP, Implied, 2),
  0xda: Op(NOP, Implied, 2),
  0xea: Op(NOP, Implied, 2),
  0xfa: Op(NOP, Implied, 2),
  0x09: Op(ORA, Immediate, 2),
  0x05: Op(ORA, ZeroPage, 3),
  0x15: Op(ORA, ZeroPageX, 4),
  0x0d: Op(ORA, Absolute, 4),
  0x1d: Op(ORA, AbsoluteX, 4, true),
  0x19: Op(ORA, AbsoluteY, 4, true),
  0x01: Op(ORA, IndexedIndirect, 6),
  0x11: Op(ORA, IndirectIndexed, 5, true),
  0x48: Op(PHA, Implied, 3),
  0x08: Op(PHP, Implied, 3),
  0x68: Op(PLA, Implied, 4),
  0x28: Op(PLP, Implied, 4),
  0x2a: Op(ROL, Accumulator, 2),
  0x26: Op(ROL, ZeroPage, 5),
  0x36: Op(ROL, ZeroPageX, 6),
  0x2e: Op(ROL, Absolute, 6),
  0x3e: Op(ROL, AbsoluteX, 7),
  0x6a: Op(ROR, Accumulator, 2),
  0x66: Op(ROR, ZeroPage, 5),
  0x76: Op(ROR, ZeroPageX, 6),
  0x6e: Op(ROR, Absolute, 6),
  0x7e: Op(ROR, AbsoluteX, 7),
  0x40: Op(RTI, Implied, 6),
  0x60: Op(RTS, Implied, 6),
  0xeb: Op(SBC, Immediate, 2),
  0xe9: Op(SBC, Immediate, 2),
  0xe5: Op(SBC, ZeroPage, 3),
  0xf5: Op(SBC, ZeroPageX, 4),
  0xed: Op(SBC, Absolute, 4),
  0xfd: Op(SBC, AbsoluteX, 4, true),
  0xf9: Op(SBC, AbsoluteY, 4, true),
  0xe1: Op(SBC, IndexedIndirect, 6),
  0xf1: Op(SBC, IndirectIndexed, 5, true),
  0x38: Op(SEC, Implied, 2),
  0xf8: Op(SED, Implied, 2),
  0x78: Op(SEI, Implied, 2),
  0x85: Op(STA, ZeroPage, 3),
  0x95: Op(STA, ZeroPageX, 4),
  0x8d: Op(STA, Absolute, 4),
  0x9d: Op(STA, AbsoluteX, 5),
  0x99: Op(STA, AbsoluteY, 5),
  0x81: Op(STA, IndexedIndirect, 6),
  0x91: Op(STA, IndirectIndexed, 6),
  0x86: Op(STX, ZeroPage, 3),
  0x96: Op(STX, ZeroPageY, 4),
  0x8e: Op(STX, Absolute, 4),
  0x84: Op(STY, ZeroPage, 3),
  0x94: Op(STY, ZeroPageX, 4),
  0x8c: Op(STY, Absolute, 4),
  0xaa: Op(TAX, Implied, 2),
  0xa8: Op(TAY, Implied, 2),
  0xba: Op(TSX, Implied, 2),
  0x8a: Op(TXA, Implied, 2),
  0x9a: Op(TXS, Implied, 2),
  0x98: Op(TYA, Implied, 2),
  0x4b: Op(ALR, Immediate, 2),
  0x0b: Op(ANC, Immediate, 2),
  0x2b: Op(ANC, Immediate, 2),
  0x6b: Op(ARR, Immediate, 2),
  0xcb: Op(AXS, Immediate, 2),
  0xa7: Op(LAX, ZeroPage, 3),
  0xb7: Op(LAX, ZeroPageY, 4),
  0xaf: Op(LAX, Absolute, 4),
  0xbf: Op(LAX, AbsoluteY, 4, true),
  0xa3: Op(LAX, IndexedIndirect, 6),
  0xb3: Op(LAX, IndirectIndexed, 5, true),
  0x87: Op(SAX, ZeroPage, 3),
  0x97: Op(SAX, ZeroPageY, 4),
  0x8f: Op(SAX, Absolute, 4),
  0x83: Op(SAX, IndexedIndirect, 6, true),
  0xc7: Op(DCP, ZeroPage, 5),
  0xd7: Op(DCP, ZeroPageX, 6),
  0xcf: Op(DCP, Absolute, 6),
  0xdf: Op(DCP, AbsoluteX, 7),
  0xdb: Op(DCP, AbsoluteY, 7),
  0xc3: Op(DCP, IndexedIndirect, 8),
  0xd3: Op(DCP, IndirectIndexed, 8),
  0xe7: Op(ISC, ZeroPage, 5),
  0xf7: Op(ISC, ZeroPageX, 6),
  0xef: Op(ISC, Absolute, 6),
  0xff: Op(ISC, AbsoluteX, 7),
  0xfb: Op(ISC, AbsoluteY, 7),
  0xe3: Op(ISC, IndexedIndirect, 8),
  0xf3: Op(ISC, IndirectIndexed, 8),
  0x27: Op(RLA, ZeroPage, 5),
  0x37: Op(RLA, ZeroPageX, 6),
  0x2f: Op(RLA, Absolute, 6),
  0x3f: Op(RLA, AbsoluteX, 7),
  0x3b: Op(RLA, AbsoluteY, 7),
  0x23: Op(RLA, IndexedIndirect, 8),
  0x33: Op(RLA, IndirectIndexed, 8),
  0x67: Op(RRA, ZeroPage, 5),
  0x77: Op(RRA, ZeroPageX, 6),
  0x6f: Op(RRA, Absolute, 6),
  0x7f: Op(RRA, AbsoluteX, 7),
  0x7b: Op(RRA, AbsoluteY, 7),
  0x63: Op(RRA, IndexedIndirect, 8),
  0x73: Op(RRA, IndirectIndexed, 8),
  0x07: Op(SLO, ZeroPage, 5),
  0x17: Op(SLO, ZeroPageX, 6),
  0x0f: Op(SLO, Absolute, 6),
  0x1f: Op(SLO, AbsoluteX, 7),
  0x1b: Op(SLO, AbsoluteY, 7),
  0x03: Op(SLO, IndexedIndirect, 8),
  0x13: Op(SLO, IndirectIndexed, 8),
  0x47: Op(SRE, ZeroPage, 5),
  0x57: Op(SRE, ZeroPageX, 6),
  0x4f: Op(SRE, Absolute, 6),
  0x5f: Op(SRE, AbsoluteX, 7),
  0x5b: Op(SRE, AbsoluteY, 7),
  0x43: Op(SRE, IndexedIndirect, 8),
  0x53: Op(SRE, IndirectIndexed, 8),
  0x80: Op(SKB, Immediate, 2),
  0x82: Op(SKB, Immediate, 2),
  0x89: Op(SKB, Immediate, 2),
  0xc2: Op(SKB, Immediate, 2),
  0xe2: Op(SKB, Immediate, 2),
  0x0c: Op(IGN, Absolute, 4),
  0x1c: Op(IGN, AbsoluteX, 4, true),
  0x3c: Op(IGN, AbsoluteX, 4, true),
  0x5c: Op(IGN, AbsoluteX, 4, true),
  0x7c: Op(IGN, AbsoluteX, 4, true),
  0xdc: Op(IGN, AbsoluteX, 4, true),
  0xfc: Op(IGN, AbsoluteX, 4, true),
  0x04: Op(IGN, ZeroPage, 3),
  0x44: Op(IGN, ZeroPage, 3),
  0x64: Op(IGN, ZeroPage, 3),
  0x14: Op(IGN, ZeroPageX, 4),
  0x34: Op(IGN, ZeroPageX, 4),
  0x54: Op(IGN, ZeroPageX, 4),
  0x74: Op(IGN, ZeroPageX, 4),
  0xd4: Op(IGN, ZeroPageX, 4),
  0xf4: Op(IGN, ZeroPageX, 4),
};
